spring:
  security:
    
  resources:
    static-locations: classpath:/static/,classpath:/view/,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  dubbo:
    application:
      name: credit-teacher
    registry:
      address: zookeeper://192.168.25.128
      port: 2181
    scan: com.credit.creditteacherweb.controller
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
server:
  port: 9091 #Tomcat端口    
    